Don't attempt to precomile zsh scripts with no zsh

diff --git a/configctl b/configctl
--- a/configctl
+++ b/configctl
@@ -205,8 +205,10 @@ checkavailable patch "patch ZNC.el"
 logdbgr "Checking for zsh."
 if command -v zsh 2>&1 >/dev/null; then
 	loginfo "Detected $(type zsh | sed 's/is/as/')."
+	ZSH_AVAILABLE=true
 else
 	logwarn "Failed to detect zsh. Precompilation will not occur."
+	ZSH_AVAILABLE=false
 fi
 
 logdbgr "Finished preparing."
@@ -346,6 +348,10 @@ action_preload() {
 }
 
 action_precompile() {
+	if ! $ZSH_AVAILABLE; then
+		logwarn "Cannot precompile zsh scripts due to missing zsh binary."
+		exit 1
+	fi
 	loginfo "Precompiling zsh scripts..."
 	logdbgr "Changing working directory to $TARGET_DIR."
 	cd $TARGET_DIR
